### ISSUE TITLE
Language labels should be styled like labels

### ISSUE THREAD

**Issue by underyx** [coala/landing-frontend#64] opened 2017-01-30 10:58 UTC
![](https://i.underyx.me/2017-01-30T11-57-32.w8bo8.png)

Instead of this we should have something like what GitHub labels look like ➡️

**Comment by sils** [comment] 2017-01-30 11:00
isn't this a dupe of #63 ?

**Comment by underyx** [comment] 2017-01-30 11:02
https://github.com/coala/landing-frontend/issues/63#issuecomment-276033629

>we can make them like the GSoC and RGSoC labels on http://projects.coala.io/#/projects

**Comment by underyx** [comment] 2017-01-30 11:02
@sils not a dupe, I'll the other one is about having python three times.

**Closed** 2017-01-30 11:47 UTC
Labels: difficulty/low
