### ISSUE TITLE
"File caching support - run only on changed file" Text not compeletly Visible

### ISSUE THREAD

**Issue by AkshJain99** [coala/landing-frontend#297] opened 2018-12-13 17:25 UTC
![screenshot_2018-12-13 coala](https://user-images.githubusercontent.com/29670791/49955942-0dcc4400-ff2a-11e8-88e8-65e813349062.png)
Either we should adjust the text or need to implement scrolling feature

**Comment by li-boxuan** [comment] 2018-12-14 01:32
Duplicate of https://github.com/coala/landing-frontend/issues/279

**Closed by li-boxuan** 2018-12-14 01:32 UTC
Labels: type/bug
